# Change these first
owner: rileyspence # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: NGS1
    url: https://ngs1m.nimrdinfrastructure.net
  - name: Modded Minecraft
    url: https://modded-map.nimrd.net
  - name: ARK
    url: ark.nimrd.net
    port: 27015
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nimrd.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Nimrod
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "This status page uses **real-time** data from our servers to give the most up-to-date status of our services."
  links: # Added a parent key to group the links
    - title: Nimrod
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
